Feature/disable ssl check
dataiku/dss-plugin-tableau-hyper pull request #9
Opened 2021-02-01 18:33 UTC by tdesfont

2021-02-01 18:34 UTC, tdesfont commented
First draft, need to add some unit tests on the configuration

2021-02-02 09:52 UTC, MayeulRousselet requested changes
The PR is not working.
The parameter ignore_ssl_check should be used to tell the tableau hyper client or the requests package to ignore SSL Certificates.

2021-02-02 11:33 UTC, tdesfont commented
Changed !

2021-02-02 18:17 UTC, MayeulRousselet requested changes
Just a nitpick request and we're gooood

2021-02-02 18:17 UTC, MayeulRousselet commented on parameter-sets/tableau-server-connection/parameter-set.json
> +
remove this blank line

2021-02-03 15:19 UTC, tdesfont commented on parameter-sets/tableau-server-connection/parameter-set.json
> +
Done in 69faa5f

2021-02-05 16:29 UTC, merged